// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * codex-vl: client-declared capabilities for fork-owned dynamic tools
 * (thread/start `capabilities` field). Requests the fork-owned builtins the
 * hosting client can serve; the TUI identity check remains the compatibility
 * fallback during the 0.151.x cycle.
 */
export type ThreadClientCapabilities = {
/**
 * Explicitly request the fork-owned `manage_loops` dynamic tool.
 */
manageLoops?: boolean, };
