// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IdentityChallenge = { version: bigint, connectionId: string, daemonBootId: string, audience: string, nonce: string, issuedAt: bigint, expiresAt: bigint, };
