// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IdentityChallenge } from "./IdentityChallenge";
import type { IdentityClaims } from "./IdentityClaims";
import type { IdentityKind } from "./IdentityKind";

export type IdentityProof = { version: string, kind: IdentityKind, challenge: IdentityChallenge, claims: IdentityClaims,
/**
 * Opaque authority proof. It is never interpreted by a client.
 */
proof: string, };
