// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IdentityLiveHost } from "./IdentityLiveHost";
import type { IdentityOrigin } from "./IdentityOrigin";

export type IdentityClaims = { issuerOwner: string, audience: string, ownerInstanceId: string, cellId: string, tmuxSession: string, incarnationId: string, launchEpoch: string, daemonBootId: string, connectionId: string, bindingId: string, origin: IdentityOrigin, scopes: Array<string>, issuedAt: string, notBefore: string, expiresAt: string, nonce: string, threadId: string | null, cwd: string | null, liveHost: IdentityLiveHost | null, };
